/** Declaration file generated by dts-gen */

export = wx_accesstoken;

declare class wx_accesstoken {
    constructor(appId: any, secret: any, redisClient: any);

    getAccessToken(): any;

    getNewAccessToken(): any;

}